# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App

on:
  workflow_run:
    workflows: ['Build and deploy Docker Image to Azure Web App']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: Set environment variables
        id: set_env
        run: |
          if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            echo "AZUREAPPSERVICE_PUBLISHPROFILE=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DEV }}" >> $GITHUB_ENV
            echo "WEB_APP_NAME=${{ secrets.WEB_APP_NAME_DEV }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/uat" ]; then
            echo "AZUREAPPSERVICE_PUBLISHPROFILE=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_UAT }}" >> $GITHUB_ENV
            echo "WEB_APP_NAME=${{ secrets.WEB_APP_NAME_UAT }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "AZUREAPPSERVICE_PUBLISHPROFILE=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PROD }}" >> $GITHUB_ENV
            echo "WEB_APP_NAME=${{ secrets.WEB_APP_NAME_PROD }}" >> $GITHUB_ENV
          fi

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ env.WEB_APP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ env.AZUREAPPSERVICE_PUBLISHPROFILE }}
