name: Build and deploy Docker Image to Azure Web App

on:
  push:
    branches:
      - dev # Development branch
      - uat # User Acceptance Testing branch
      - master # Production branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        id: set_env
        run: |
          if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            echo "ACR_USERNAME=${{ secrets.ACR_USERNAME_DEV }}" >> $GITHUB_ENV
            echo "ACR_PASSWORD=${{ secrets.ACR_PASSWORD_DEV }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/uat" ]; then
            echo "ACR_USERNAME=${{ secrets.ACR_USERNAME_UAT }}" >> $GITHUB_ENV
            echo "ACR_PASSWORD=${{ secrets.ACR_PASSWORD_UAT }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "ACR_USERNAME=${{ secrets.ACR_USERNAME_PROD }}" >> $GITHUB_ENV
            echo "ACR_PASSWORD=${{ secrets.ACR_PASSWORD_PROD }}" >> $GITHUB_ENV
          fi

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: ${{ env.ACR_USERNAME }}
          # Container registry password
          password: ${{ env.ACR_PASSWORD }}
          # Container registry server url
          login-server: ${{ env.ACR_USERNAME }}.azurecr.io

      - uses: actions/checkout@v3
      - name: Build and push the Docker image
        run: |
          IMAGE_NAME=${{ env.ACR_USERNAME }}.azurecr.io/sample-app-aoai-chatgpt
          DATE_TAG=$(date +'%Y-%m-%d')
          FULL_TAG=${IMAGE_NAME}:${DATE_TAG}_$GITHUB_RUN_NUMBER
          LATEST_TAG=${IMAGE_NAME}:latest
          docker build . --file WebApp.Dockerfile --tag ${FULL_TAG};
          docker tag ${FULL_TAG} ${IMAGE_NAME}:latest;
          docker push ${FULL_TAG};
          docker push ${IMAGE_NAME}:latest;

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Azure Container Registry Login
  #       uses: Azure/docker-login@v1
  #       with:
  #         # Container registry username
  #         username: ${{ env.ACR_USERNAME }}
  #         # Container registry password
  #         password: ${{ env.ACR_PASSWORD }}
  #         # Container registry server url
  #         login-server: ${{ env.ACR_USERNAME }}.azurecr.io

  #     - name: 'Deploy to Azure Web App'
  #       uses: azure/webapps-deploy@v2
  #       id: deploy-to-webapp
  #       with:
  #         app-name: 'dataplatform-core-chatgpt-webapp-d'
  #         slot-name: 'Production'
  #         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
  #         images: "${IMAGE_NAME}:latest"
